-- ----------------------------
-- Records of tbl_book
-- ----------------------------
INSERT INTO `t_book`(id,name,price,author,publisher,book_num,page_num,category,description) VALUES ('1', 'JAVA核心技术', '99.00', 'Horstmann Cay S.', '电子工业出版社', '9787121133626', '600', '软件与程序设计', 'CayS.Horstmann等编著，公飞编译的《Java核心技术》(CoreJava)自第1版出版以来，一直备受广大Java程序设计人员的青睐，畅销不衰，是Java经典书籍。第8版针对JavaSE6平台进行了全面更新，囊括了Java平台标准版(JavaSE/J2SE)的全部基础知识，提供了大量完整且具有实际意义的应用实例，详细介绍了Java语言基础知识、面向对象程序设计、接口与内部类、事件监听器模型、swing图形用户界面程序设计、打包应用程序、异常处理、登录与调试、泛型程序设计、集合框架、多线程等内容。');
INSERT INTO `t_book`(id,name,price,author,publisher,book_num,page_num,category,description) VALUES ('2', 'UNIX技术手册', '69.00', 'Kemeth Rosen.', '电子工业出版社', '9787121047619', '671', '软件与程序设计', '本书全面描述了UNIX系统及其各种变体的基本用法及高级特性，包括 Linux、Solaris、HP-UX、AIX、FreeBSD和Mac OS X等，充分反映了UNIX系统发展的最新成果和前沿技术，全面阐述了UNIX系统的功能特性，同时也介绍了UNIX的各种工具、实用程序和应用程序，涉及UNIX系统管理、网络管理、UNIX工具及编程、企业应用等主题，对初学者和资深用户都极具价值。对于有志于学习UNIX系统或各种UNIX变体的人，本书是一本很有实用价值的优秀参考书，适用从事UNIX系统管理和应用开发的人员参考。');
INSERT INTO `t_book`(id,name,price,author,publisher,book_num,page_num,category,description) VALUES ('3', 'Oracle9i初学者指南', '108.00', 'Michael Abbey', '机械工业', '9787111099277', '360', '软件与程序设计', '本书由著名的Oracle畅销书作家KevinLoney、GeorgeKoch以及TUSC的多位技术专家合力打造，涵盖了Oracle9i数据库的所有特性。本书的技术主题主要包括：使用倒叙查询使数据保持在未提交前的状态创建、查询和管理外部表执行和调整SQL查询使用SQL*PLUS生成复杂的报表使用PL／SQL创建触发器、存储过程、函数和包类型、对象视图和方法的实现使用SQL*Loader将数据从外部文件导入Oracle据库表中使用SQLJ、JDBC和XML开发健壮的数据库应用利用Oracle9i数据字典和优化程序深入了解Oracle9iApplicationServer（Oracle9iAS）管理、调整、备份和恢复Oracle9i数据库本书的前几版均在亚马逊上取得极佳的销售成绩,，中译本（（Oracle8完全参考手册》也是国内畅销书。本书在前几版的基础上结合Orade9i的新特性，更加全面地介绍了Oracle数据库，是读者全面了解Oracle的必备参考书。');
INSERT INTO `t_book`(id,name,price,author,publisher,book_num,page_num,category,description) VALUES ('4', 'JSP设计(第三版)', '59.00', '鲍格斯坦 ', '中国电力出版社', '9787508322735', '778', '软件与程序设计', '《JSP设计》(第3版)自1999处JSP 1.0发布以来，JavaServer Pages（JSP）可谓掀起了一场风暴，其追随者蜂拥而至。JSP为企业Java开发人员提供了一个开发动态Web网站和Web应用的灵活工具。随着JSP标准标记库（JSTL）的引入，JSP规范第一版中略显粗糙的方面也有了大幅改进，JSP 2.0则将此技术又推向了一个新的高度。 《JSP设计》（第三版）得到了充分的修订和更新，以涵盖JSP 2.0和JSTL 1.1规范。其中详细介绍了JSP 2.0中新增的表达式语言（EL）、JSTL 1.1标记库和新的函数库、支持定制标记库开发（而无须Java代码）的新标记文件格式、简化的Java标记库API、在JSP XML语法方面所做出的改进等等。不仅如此，在此还详尽地描述了Apache Tomcat服务器的建立、JSP和JSTL语法和特征、错误处理和调试、鉴别和个人化、数据库访问、XML处理和国际化等诸多内容。');
INSERT INTO `t_book`(id,name,price,author,publisher,book_num,page_num,category,description) VALUES ('5', 'JAVA SERVLET 编程(第二版)', '38.00', '亨特', '中国电力出版社', '9787508308449', '678', '软件与程序设计', '在过去的几年里，Java servlet已经在服务器端开发领域引起了轰动。现在，随着Servlet APl 2．3版的引入，服务器端的servlet将把Java Web软件开发带向更高的层次。 为更好地生成动态网页，servlet提供了快捷、强大、灵活的开发环境。开发出来的servlet可以在服务器的进程空间里运行，并能同时处理多个请求，因此，采用servlet方案系统的性能将会比其他解决方案优秀得多。servlet可以使用各种Java API和第三方厂商提供的组件类，而这些都是Java 2企业版(J2EE)的有机组成部分。当然，最值得称道的便是servlet的平台无关性——真正做到了“一次编写，到处运行”(Write once，Serve anywhere)。');
INSERT INTO `t_book`(id,name,price,author,publisher,book_num,page_num,category,description) VALUES ('6', 'XML 高级编程(第2版)', '97.00', 'Thiru Thangarathinam', '清华大学出版社', '9787302194781', '7752', '软件与程序设计', '《XML高级编程》会指出获取这些工具或技术支持的途径。《XML高级编程》既关注基于Microsoft的技术，也关注基于Java的技术，因此有时读者必须使用这些开发商特有的开发工具和平台来完成书中的示例。0.2《XML高级编程》读者对象《XML高级编程》旨在向读者提供当今关于XML的最新和最优信息，以及基于XML的最新技术和最新性能。读者需要具备理解基本编程技术，如C#或Java的能力。如果读者能理解这些编程语言，对于阅读《XML高级编程》则不会有太大困难。如果读者对XML比较陌生，那么最好先阅读DavidHunter等人合著的BeginningXML（由Wrox出版，ISBN：978-0-7645-7077-3）一书，以便掌握一些XML的基础知识。《XML高级编程》同时适用于Microsoft或Java开发人员。书中将有不同的章节分别着重介绍这两种编程技术。0.3《XML高级编程》主要内容《XML高级编程》对ASP.NET2.0版本中发生的巨大变化进行了回顾，并且详细介绍了ASP.NET2.0的各个主要新特性。');
INSERT INTO `t_book`(id,name,price,author,publisher,book_num,page_num,category,description) VALUES ('7', '精通STRUTS:基于MVC的JAVA WEB设计与开发', '36.00', '孙卫琴', '电子工业出版社', '7121000520', '512', '软件与程序设计', 'struts是目前非常流行的基于mvc的java web框架。本书详细介绍了在最新的struts1.1以及不久将推出的struts1.2版本上设计和开发java web应用的各种技术。本书第1章到第3章为入门篇，通过两个struts应用实例，引导读者把握设计、开发和部署struts应用的整体流程，充分体会 struts框架在开放大型、可扩展的web应用方面发挥的优势。第4章到第7章深入探讨了struts框架的核心组件actionservlet和 requestprocessor的实现原理，详细介绍了开发struts应用的模型、视图和控制器的各种技术，细致的描述了struts配置文件的每个元素的使用方法。第8章到第9章介绍了开发struts应用的一些实用技术，如struts框架的扩展点、struts应用的国际化，validator 验证框架和异常处理机制等。');
INSERT INTO `t_book`(id,name,price,author,publisher,book_num,page_num,category,description) VALUES ('8', '精通HIBERNATE：JAVA对象持久化技术详解', '44.00', '孙卫琴', '电子工业出版社', '9787121093739', '600', '软件与程序设计', '本书在第一版基础上，理论内容更新，更加注重理论与实践的结合，有大量具有典型性和实用价值的Hibernate应用实例。全书将详细介绍运用目前最成熟的Hibernate 3.3版本进行Java对象持久化的技术，既能掌握用Hibernate工具对这两种模型进行映射的技术，又能获得设计与开发Java对象模型和关系数据模型的经验。光盘包括本书范例源程序、涉及软件的最新版本的安装程序，以及配套的语音讲座。');
INSERT INTO `t_book`(id,name,price,author,publisher,book_num,page_num,category,description) VALUES ('9', 'SPRING IN ACTION中文版', '29.00', '沃尔斯', '人民邮电出版社', '9787115143150', '382', '软件与程序设计', '《Spring in Action中文版》适合所有Java开发人员，特别是对企业级Java开发人员更有帮助。《Spring in Action中文版》将循序渐进地指导读者浏览贯穿《Spring in Action中文版》的复杂示例。Spring最突出之处在于它使企业级系统开发变得简单，所以，企业级系统开发人员会更加欣赏《Spring in Action中文版》中的示例代码。《Spring in Action中文版》最后4章描述了Spring是如何为Web层开发提供支持的，如果你是一位Web开发人员，你会发现《Spring in Action中文版》的最后一部分特别有用。');
INSERT INTO `t_book`(id,name,price,author,publisher,book_num,page_num,category,description) VALUES ('10', '精通EJB 3.0', '44.00', '罗时飞', '电子工业出版社', '7121032724', '482', '软件与程序设计', '本书是关于ejb 3.0的专业技术教程，专注于ejb的概念、方法、开发过程的介绍。同时，本书还研究许多高端的ejb知识，使得开发者能够真正理解和掌握ejb，实践出真知。通过阅读此书，开发者将精通ejb。.\r\n全书共分为4个部分：第一部分对ejb编程基础进行介绍，概要性地对ejb进行了阐述；第二部分重点关注ejb编程的具体内容和过程，向开发者展示了如何使用会话bean、将会话bean发布为web服务、消息驱动bean；第三部分专注于高级ejb专题；第四部分是附录，收集了ejb组件技术相关的其他内容。..\r\n本书适合作为java程序员、网站开发人员和系统分析员的参考书');